# Generated by Django 3.2.13 on 2022-11-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_review_like_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcomment',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
