# Generated by Django 3.2.13 on 2022-11-07 01:24

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_wishitem_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image_two',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='review',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
