# Generated by Django 3.2.13 on 2022-11-07 01:55

from django.conf import settings
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_wishitem_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wishlist',
            field=models.ManyToManyField(related_name='product_wishlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='WishItem',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
