# Generated by Django 3.2.13 on 2022-11-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_reviewcomment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcomment',
            name='content',
            field=models.TextField(),
        ),
    ]
