# Generated by Django 3.2.13 on 2022-11-07 02:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0003_auto_20221107_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='wishlist',
            field=models.ManyToManyField(null=True, related_name='product_wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
