# Generated by Django 3.2.13 on 2022-11-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_reviewcomment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='contury',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
