# Generated by Django 3.2.13 on 2022-11-02 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_review_contury'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='contury',
            new_name='country',
        ),
    ]
