# Generated by Django 3.2.13 on 2022-11-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(default=1, upload_to='images/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
